//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntp_Proje.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ntp_Proje.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _138659 {
            get {
                object obj = ResourceManager.GetObject("138659", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _220_2205714_get_the_latest_movies_data_src_kodi_tv {
            get {
                object obj = ResourceManager.GetObject("220-2205714_get-the-latest-movies-data-src-kodi-tv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _220_2205714_get_the_latest_movies_data_src_kodi_tv1 {
            get {
                object obj = ResourceManager.GetObject("220-2205714_get-the-latest-movies-data-src-kodi-tv1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _238_2381122_south_park_bigger_longer_and_uncut {
            get {
                object obj = ResourceManager.GetObject("238-2381122_south-park-bigger-longer-and-uncut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _295128 {
            get {
                object obj = ResourceManager.GetObject("295128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _2951281 {
            get {
                object obj = ResourceManager.GetObject("2951281", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _2c26ccec90ab5e119b194beb064a6a9d__sherlock_poster_watch_sherlock {
            get {
                object obj = ResourceManager.GetObject("2c26ccec90ab5e119b194beb064a6a9d--sherlock-poster-watch-sherlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _3840x2160_Walter_White_de_Breaking_Bad_Wallpaper_4K_Ultra_HD_scaled {
            get {
                object obj = ResourceManager.GetObject("3840x2160-Walter-White-de-Breaking-Bad-Wallpaper-4K-Ultra-HD-scaled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _3D_glass_film_reel_reels_light_lighting_5252_wallhere_com {
            get {
                object obj = ResourceManager.GetObject("3D-glass-film-reel-reels-light-lighting-5252-wallhere.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _5480605_mr_robot_wallpapers {
            get {
                object obj = ResourceManager.GetObject("5480605-mr-robot-wallpapers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _5480605_mr_robot_wallpapers1 {
            get {
                object obj = ResourceManager.GetObject("5480605-mr-robot-wallpapers1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Action {
            get {
                object obj = ResourceManager.GetObject("Action", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Admin_girişi {
            get {
                object obj = ResourceManager.GetObject("Admin girişi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Animation_icon {
            get {
                object obj = ResourceManager.GetObject("Animation-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap azvector181100097 {
            get {
                object obj = ResourceManager.GetObject("azvector181100097", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap better_call_saul_tv_series_folder_icon_2015512 {
            get {
                object obj = ResourceManager.GetObject("better_call_saul_tv_series_folder_icon_2015512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap büyüteç {
            get {
                object obj = ResourceManager.GetObject("büyüteç", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Comedy_icon {
            get {
                object obj = ResourceManager.GetObject("Comedy-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap d0932b3ed34581f4f811626a242c4ce3 {
            get {
                object obj = ResourceManager.GetObject("d0932b3ed34581f4f811626a242c4ce3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap d66qy9l_3cdd9fd2_64b9_4fee_96de_d3400927d4d1 {
            get {
                object obj = ResourceManager.GetObject("d66qy9l-3cdd9fd2-64b9-4fee-96de-d3400927d4d1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap d66qy9l_3cdd9fd2_64b9_4fee_96de_d3400927d4d11 {
            get {
                object obj = ResourceManager.GetObject("d66qy9l-3cdd9fd2-64b9-4fee-96de-d3400927d4d11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap d8pog5j_8db3d739_4a41_44e3_a795_9b38b6699f70 {
            get {
                object obj = ResourceManager.GetObject("d8pog5j-8db3d739-4a41-44e3-a795-9b38b6699f70", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap d8rlcey_401beb09_fd16_4f42_a244_8102a9a51743 {
            get {
                object obj = ResourceManager.GetObject("d8rlcey-401beb09-fd16-4f42-a244-8102a9a51743", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap d9uy35a_a6002dca_6fe4_45b4_a2b3_5912bb8c88b2 {
            get {
                object obj = ResourceManager.GetObject("d9uy35a-a6002dca-6fe4-45b4-a2b3-5912bb8c88b2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap d9wp3ib_52ee4eae_aa31_4b9d_824b_d4a0c22eece9 {
            get {
                object obj = ResourceManager.GetObject("d9wp3ib-52ee4eae-aa31-4b9d-824b-d4a0c22eece9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap daqmoe5_c62643ef_b1fb_4902_a73f_c943ae7b3008 {
            get {
                object obj = ResourceManager.GetObject("daqmoe5-c62643ef-b1fb-4902-a73f-c943ae7b3008", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap db2xnsv_4198b89d_cf4e_485b_91b3_5d253df7f41b {
            get {
                object obj = ResourceManager.GetObject("db2xnsv-4198b89d-cf4e-485b-91b3-5d253df7f41b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap db5rc4u_652afe47_3780_4387_ac69_c461ac854099 {
            get {
                object obj = ResourceManager.GetObject("db5rc4u-652afe47-3780-4387-ac69-c461ac854099", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap dc1tca9_549e1c67_018c_470a_8b06_5ebe57a0f4b8 {
            get {
                object obj = ResourceManager.GetObject("dc1tca9-549e1c67-018c-470a-8b06-5ebe57a0f4b8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap dcdzkdg_e061dea3_4d75_4337_80c7_86e542f93c1e {
            get {
                object obj = ResourceManager.GetObject("dcdzkdg-e061dea3-4d75-4337-80c7-86e542f93c1e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap dce38iv_c126dcac_1629_4a7b_b410_4eb8546227a7 {
            get {
                object obj = ResourceManager.GetObject("dce38iv-c126dcac-1629-4a7b-b410-4eb8546227a7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap dcsmdet_8ec68ab0_d6ca_42f6_9892_87a7853fbe50 {
            get {
                object obj = ResourceManager.GetObject("dcsmdet-8ec68ab0-d6ca-42f6-9892-87a7853fbe50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap dddd {
            get {
                object obj = ResourceManager.GetObject("dddd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap ddk4xh6_959a50f6_9ece_4a0e_8ea3_7c32c423e187 {
            get {
                object obj = ResourceManager.GetObject("ddk4xh6-959a50f6-9ece-4a0e-8ea3-7c32c423e187", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap ddk4xh6_959a50f6_9ece_4a0e_8ea3_7c32c423e1871 {
            get {
                object obj = ResourceManager.GetObject("ddk4xh6-959a50f6-9ece-4a0e-8ea3-7c32c423e1871", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap dedtfe8_49af03a6_6155_44b0_a3ec_951c77e10b72 {
            get {
                object obj = ResourceManager.GetObject("dedtfe8-49af03a6-6155-44b0-a3ec-951c77e10b72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap dedtfe8_49af03a6_6155_44b0_a3ec_951c77e10b721 {
            get {
                object obj = ResourceManager.GetObject("dedtfe8-49af03a6-6155-44b0-a3ec-951c77e10b721", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Drama_icon {
            get {
                object obj = ResourceManager.GetObject("Drama-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap e27c8735da98ec6ccdcf12e258b26475 {
            get {
                object obj = ResourceManager.GetObject("e27c8735da98ec6ccdcf12e258b26475", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap e27c8735da98ec6ccdcf12e258b264751 {
            get {
                object obj = ResourceManager.GetObject("e27c8735da98ec6ccdcf12e258b264751", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap e43d969b4b8fcbc06008b65f9673d339__peaky_blinders_cillian_murphy {
            get {
                object obj = ResourceManager.GetObject("e43d969b4b8fcbc06008b65f9673d339--peaky-blinders-cillian-murphy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap giriş {
            get {
                object obj = ResourceManager.GetObject("giriş", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Horror_icon {
            get {
                object obj = ResourceManager.GetObject("Horror-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap inception_movie_folder_icon512 {
            get {
                object obj = ResourceManager.GetObject("inception_movie_folder_icon512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1063694018_170667a {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1063694018-170667a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1221025677_170667a {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1221025677-170667a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1221025677_170667a1 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1221025677-170667a1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1221025677_170667a2 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1221025677-170667a2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap milky_way_2695569__480 {
            get {
                object obj = ResourceManager.GetObject("milky-way-2695569__480", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap milky_way_2750627_960_720 {
            get {
                object obj = ResourceManager.GetObject("milky-way-2750627_960_720", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap movies_folder_icon_17 {
            get {
                object obj = ResourceManager.GetObject("movies-folder-icon-17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap pattern_g6c16ef191_1280 {
            get {
                object obj = ResourceManager.GetObject("pattern-g6c16ef191_1280", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap peaky_blinders__tv_series_folder_icon_v1_by_dyiddo_d81gsbw_fullview {
            get {
                object obj = ResourceManager.GetObject("peaky_blinders__tv_series_folder_icon_v1_by_dyiddo_d81gsbw-fullview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_arrow_symbol_computer_icons_back_angle_rectangle_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-arrow-symbol-computer-icons-back-angle-rectangle-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_dirili_erturul_folder_icon_diriliş_ertuğrul_folder_icon_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-dirili-erturul-folder-icon-diriliş-ertuğrul-folder-icon-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_marvel_fantastic_four_folder_icon_fantasticfour2015_a_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-marvel-fantastic-four-folder-icon-fantasticfour2015-a-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_sherlock_folder_icons_sherlock_smart_folder_3_19_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-sherlock-folder-icons-sherlock-smart-folder-3-19-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap sssssss_aaaaaaaaaaa_ddddddddd_fffffffff_rrrrrrr {
            get {
                object obj = ResourceManager.GetObject("sssssss-aaaaaaaaaaa-ddddddddd-fffffffff-rrrrrrr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap thumb_1920_774364 {
            get {
                object obj = ResourceManager.GetObject("thumb-1920-774364", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap turkiyede_cekilecek_yabanci_dizi_ve_filmlere_tesvik_verilecek_1575100915 {
            get {
                object obj = ResourceManager.GetObject("turkiyede-cekilecek-yabanci-dizi-ve-filmlere-tesvik-verilecek-1575100915", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap turkiyede_cekilecek_yabanci_dizi_ve_filmlere_tesvik_verilecek_15751009151 {
            get {
                object obj = ResourceManager.GetObject("turkiyede-cekilecek-yabanci-dizi-ve-filmlere-tesvik-verilecek-15751009151", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap turkiyede_cekilecek_yabanci_dizi_ve_filmlere_tesvik_verilecek_15751009152 {
            get {
                object obj = ResourceManager.GetObject("turkiyede-cekilecek-yabanci-dizi-ve-filmlere-tesvik-verilecek-15751009152", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap tv_series_4k_peaky_blinders_wallpaper_preview {
            get {
                object obj = ResourceManager.GetObject("tv-series-4k-peaky-blinders-wallpaper-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap üye_girişi {
            get {
                object obj = ResourceManager.GetObject("üye girişi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap wallpapersden_com_darth_vader_vs_obi_wan_kenobi_hd_cool_star_wars_1920x1200 {
            get {
                object obj = ResourceManager.GetObject("wallpapersden.com_darth-vader-vs-obi-wan-kenobi-hd-cool-star-wars_1920x1200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap wkiSLTZq3Jw {
            get {
                object obj = ResourceManager.GetObject("wkiSLTZq3Jw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap yeni_üye {
            get {
                object obj = ResourceManager.GetObject("yeni üye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
