//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntp_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiziKaydetme
    {
        public int Diziid { get; set; }
        public string DiziAdi { get; set; }
        public string DiziTuru { get; set; }
        public string DiziYonetmen { get; set; }
        public string Diziimdb { get; set; }
        public string DiziSezonSayisi { get; set; }
        public string DiziTarzi { get; set; }
        public string DiziYili { get; set; }
        public string DiziFilitreleme { get; set; }
    }
}
