//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntp_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmKaydetme
    {
        public int Filmid { get; set; }
        public string FilmAdi { get; set; }
        public string FilmTuru { get; set; }
        public string FilmYonetmen { get; set; }
        public string Filmimdb { get; set; }
        public string FilmSeriSayisi { get; set; }
        public string FilmTarzi { get; set; }
        public string FilmYili { get; set; }
        public string FilmFilitreleme { get; set; }
    }
}
