//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntp_Proje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ntp_ProjeEntities : DbContext
    {
        public Ntp_ProjeEntities()
            : base("name=Ntp_ProjeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DiziKaydetme> DiziKaydetme { get; set; }
        public virtual DbSet<FilmKaydetme> FilmKaydetme { get; set; }
        public virtual DbSet<KullaniciKaydetme> KullaniciKaydetme { get; set; }
    }
}
